services:
  - type: web
    name: it-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: it-inventory-db
          property: connectionString

databases:
  - name: it-inventory-db
    databaseName: inventory
    user: inventory_user
